services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisition-app-dev
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    restart: unless-stopped

  # Neon Local sadece devde
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: neon-local
    ports:
      - '5432:5432'
    env_file:
      - .env.development
